export const BOOK_UPLOADS_FILES = './uploads/elibrary/books'
export const BOOK_GET_UPLOADS_FILES = '/elibrary/books'
export const BOOK_CATEGORY_UPLOADS_FILES = './uploads/elibrary/category'
export const BOOK_CATEGORY_GET_UPLOADS_FILES = '/elibrary/category'
export const BOOK_IMAGE_UPLOADS_FILES = './uploads/elibrary/image'
export const BOOK_IMAGE_GET_UPLOADS_FILES = '/elibrary/image'
